version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - MARIADB_USER=moodle
      - MARIADB_DATABASE=moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  moodle:
    image: 'bitnami/moodle:3.9.0'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_NAME=moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/Users/trustokoroego/project/moodle-project/data:/bitnami/moodle'
    depends_on:
      - mariadb
  jobe:
    image: trampgeek/jobeinabox:latest
    ports:
      - '40000:80'
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local